import type { Metadata } from "next";
import localFont from "next/font/local";
import { NavBar } from '@/components/NavBar'
import "./globals.css";
import { Suspense } from 'react';
import { PlacesProvider } from '@/contexts/PlacesContext';
import { Toaster } from "@/components/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PlacesProvider>
          <NavBar />
          <div id="root-layout">
          <Suspense fallback={<div>Loading...</div>}>
            {children}
            </Suspense>
          </div>
        </PlacesProvider>
        <Toaster />
      </body>
    </html>
  );
}
